### ISSUE TITLE
Is there any way to use ember-states with ember-cli?

### ISSUE THREAD

**Issue by atduskgreg** [emberjs/ember-states#15]
ember-states doesn't export a module so it can't be imported in the usual way. It can be imported via script tag after the transpiled application js, but that means that StateManager sub-classes can't be used in app.js.

Is there a solution to this problem?

**Comment by ebryn** [comment]
Just use `app.import`: http://www.ember-cli.com/#standard-non-amd-asset

**Comment by atduskgreg** [comment]
@ebryn Will this work even though ember-states isn't a bower_component? I tried adding app.import("vendor/ember-states.js") to Brocfile.js and that didn't seem to work. What am I missing?

**Comment by stefanpenner** [comment]
yes you can import anything from vendor/*
