### ISSUE TITLE
Transition is not accesible from entry/exit hook

### ISSUE THREAD

**Issue by dschmidt** [emberjs/ember-states#7]
Hey,

Documentation says that entry/exit hook get a transition object as second parameter. 

https://github.com/emberjs/ember-states/blob/master/packages/ember-states/lib/state_manager.js#L338

That doesn't work for me: entry/exit only get a single parameter in my setup - which is the state manager itself, see demo here:

http://emberjs.jsbin.com/OMovuyu/16/edit

Thanks in advance

**Comment by krisselden** [comment]
Closing this issue since it is very stale and currently refactoring to make it more idiomatic of current ember practices.
